# Generated by Django 3.1.5 on 2021-01-20 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-datetime_from', '-datetime_to', 'room']},
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='test', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(verbose_name='Начало бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(verbose_name='Окончание бронирования'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-datetime_from', '-datetime_to'], name='reservation_datetim_e62ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room'], name='reservation_room_id_386ecf_idx'),
        ),
    ]
