# Generated by Django 3.1.5 on 2021-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210120_1008'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_datetim_e62ebe_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_room_id_386ecf_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(db_index=True, verbose_name='Начало бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(db_index=True, verbose_name='Окончание бронирования'),
        ),
    ]
