# Generated by Django 3.1.5 on 2021-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210120_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(verbose_name='Начало бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(verbose_name='Окончание бронирования'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-datetime_from', '-datetime_to'], name='reservation_datetim_e62ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room'], name='reservation_room_id_386ecf_idx'),
        ),
    ]
